#!/bin/bash
echo "========================================"
echo "  Iniciando servidor PHP para Onoxfri"
echo "========================================"
echo ""
echo "Puerto: 3000"
echo "Directorio: $(pwd)"
echo ""
echo "Presiona Ctrl+C para detener el servidor"
echo ""
echo "========================================"
php -S localhost:3000 -t .
echo ""
echo "========================================"
echo "¡Servidor iniciado correctamente!"
echo ""
echo "URLs disponibles:"
echo "- http://localhost:3000/ (Inicio)"
echo "- http://localhost:3000/test-db (Prueba BD)"
echo "- http://localhost:3000/api/auth/login (Login)"
echo "- http://localhost:3000/api/products (Productos)"
echo "========================================"